import enum

from sqlalchemy import Column, Integer, ForeignKey, DateTime, Float, Text, Enum
from sqlalchemy.orm import relationship
from datetime import datetime

from traitor.core.data import Base

class SummaryTimeframe(enum.Enum):
    DAY = "24h"
    WEEK = "7d"
    MONTH = "30d"

class CoinNewsSummary(Base):
    __tablename__ = 'coin_news_summaries'

    id = Column(Integer, primary_key=True, autoincrement=True)
    coin_id = Column(Integer, ForeignKey('coins.id', ondelete="CASCADE"), nullable=False)
    
    # '24h', '7d', '30d'
    timeframe = Column(Enum(SummaryTimeframe))
    
    # Mathematical average of the sentiment of the analyzed articles
    sentiment_score = Column(Float, nullable=True) 
    
    # The text generated by the AI (The "Meta-Summary")
    content = Column(Text, nullable=True)
    
    date_generated = Column(DateTime, default=datetime.utcnow)


    def __repr__(self):
        return f"<CoinSummary(coin={self.coin_id}, frame={self.timeframe}, score={self.sentiment_score})>"