from sqlalchemy import Column, Integer, String, ForeignKey, DateTime, Float, Text
from sqlalchemy.orm import relationship
from datetime import datetime

from traitor.core.data import Base

class CoinSummary(Base):
    __tablename__ = 'coin_summaries'

    id = Column(Integer, primary_key=True, autoincrement=True)
    coin_id = Column(Integer, ForeignKey('coins.id'), nullable=False)
    
    # '24h', '7d', '30d'
    timeframe = Column(String, nullable=False) 
    
    # Mathematical average of the sentiment of the analyzed articles
    sentiment_score = Column(Float, nullable=True) 
    
    # The text generated by the AI (The "Meta-Summary")
    content = Column(Text, nullable=True)
    
    date_generated = Column(DateTime, default=datetime.utcnow)

    # Relationships
    coin = relationship("Coin", backref="summaries")

    def __repr__(self):
        return f"<CoinSummary(coin={self.coin_id}, frame={self.timeframe}, score={self.sentiment_score})>"